// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: notify/notify.proto

package notify

import (
	common "github.com/winc-link/iot-cloud-proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DriverStatus int32

const (
	DriverStatus_Stop  DriverStatus = 0
	DriverStatus_Start DriverStatus = 1
)

// Enum value maps for DriverStatus.
var (
	DriverStatus_name = map[int32]string{
		0: "Stop",
		1: "Start",
	}
	DriverStatus_value = map[string]int32{
		"Stop":  0,
		"Start": 1,
	}
)

func (x DriverStatus) Enum() *DriverStatus {
	p := new(DriverStatus)
	*p = x
	return p
}

func (x DriverStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DriverStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_notify_notify_proto_enumTypes[0].Descriptor()
}

func (DriverStatus) Type() protoreflect.EnumType {
	return &file_notify_notify_proto_enumTypes[0]
}

func (x DriverStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DriverStatus.Descriptor instead.
func (DriverStatus) EnumDescriptor() ([]byte, []int) {
	return file_notify_notify_proto_rawDescGZIP(), []int{0}
}

type DriverStatusNotifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HappenTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=happenTime,proto3" json:"happenTime,omitempty"`
	Status     DriverStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=notify.DriverStatus" json:"status,omitempty"`
	DriverId   string                 `protobuf:"bytes,3,opt,name=DriverId,proto3" json:"DriverId,omitempty"`
}

func (x *DriverStatusNotifyRequest) Reset() {
	*x = DriverStatusNotifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_notify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverStatusNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverStatusNotifyRequest) ProtoMessage() {}

func (x *DriverStatusNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_notify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverStatusNotifyRequest.ProtoReflect.Descriptor instead.
func (*DriverStatusNotifyRequest) Descriptor() ([]byte, []int) {
	return file_notify_notify_proto_rawDescGZIP(), []int{0}
}

func (x *DriverStatusNotifyRequest) GetHappenTime() *timestamppb.Timestamp {
	if x != nil {
		return x.HappenTime
	}
	return nil
}

func (x *DriverStatusNotifyRequest) GetStatus() DriverStatus {
	if x != nil {
		return x.Status
	}
	return DriverStatus_Stop
}

func (x *DriverStatusNotifyRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

var File_notify_notify_proto protoreflect.FileDescriptor

var file_notify_notify_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x1a, 0x13, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x01, 0x0a, 0x19, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x3a, 0x0a, 0x0a, 0x68, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0a, 0x68, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2c, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x44,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x2a, 0x23, 0x0a, 0x0c, 0x44, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x10, 0x01, 0x32, 0x64, 0x0a, 0x0f,
	0x52, 0x70, 0x63, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12,
	0x51, 0x0a, 0x12, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x21, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x44,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x77, 0x69, 0x6e, 0x63, 0x2d, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x69, 0x6f, 0x74, 0x2d, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notify_notify_proto_rawDescOnce sync.Once
	file_notify_notify_proto_rawDescData = file_notify_notify_proto_rawDesc
)

func file_notify_notify_proto_rawDescGZIP() []byte {
	file_notify_notify_proto_rawDescOnce.Do(func() {
		file_notify_notify_proto_rawDescData = protoimpl.X.CompressGZIP(file_notify_notify_proto_rawDescData)
	})
	return file_notify_notify_proto_rawDescData
}

var file_notify_notify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notify_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_notify_notify_proto_goTypes = []interface{}{
	(DriverStatus)(0),                 // 0: notify.DriverStatus
	(*DriverStatusNotifyRequest)(nil), // 1: notify.DriverStatusNotifyRequest
	(*timestamppb.Timestamp)(nil),     // 2: google.protobuf.Timestamp
	(*common.CommonResponse)(nil),     // 3: common.CommonResponse
}
var file_notify_notify_proto_depIdxs = []int32{
	2, // 0: notify.DriverStatusNotifyRequest.happenTime:type_name -> google.protobuf.Timestamp
	0, // 1: notify.DriverStatusNotifyRequest.status:type_name -> notify.DriverStatus
	1, // 2: notify.RpcDriverNotify.DriverStatusNotify:input_type -> notify.DriverStatusNotifyRequest
	3, // 3: notify.RpcDriverNotify.DriverStatusNotify:output_type -> common.CommonResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_notify_notify_proto_init() }
func file_notify_notify_proto_init() {
	if File_notify_notify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_notify_notify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DriverStatusNotifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notify_notify_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notify_notify_proto_goTypes,
		DependencyIndexes: file_notify_notify_proto_depIdxs,
		EnumInfos:         file_notify_notify_proto_enumTypes,
		MessageInfos:      file_notify_notify_proto_msgTypes,
	}.Build()
	File_notify_notify_proto = out.File
	file_notify_notify_proto_rawDesc = nil
	file_notify_notify_proto_goTypes = nil
	file_notify_notify_proto_depIdxs = nil
}
