// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.14.0
// source: batch/batch.proto

package batch

import (
	context "context"
	common "github.com/winc-link/iot-cloud-proto/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RpcPropertyClient is the client API for RpcProperty service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcPropertyClient interface {
	//设备批量上报
	DeviceBatchReport(ctx context.Context, in *DeviceBatchReportRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
}

type rpcPropertyClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcPropertyClient(cc grpc.ClientConnInterface) RpcPropertyClient {
	return &rpcPropertyClient{cc}
}

func (c *rpcPropertyClient) DeviceBatchReport(ctx context.Context, in *DeviceBatchReportRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, "/batch.RpcProperty/DeviceBatchReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcPropertyServer is the server API for RpcProperty service.
// All implementations must embed UnimplementedRpcPropertyServer
// for forward compatibility
type RpcPropertyServer interface {
	//设备批量上报
	DeviceBatchReport(context.Context, *DeviceBatchReportRequest) (*common.CommonResponse, error)
	mustEmbedUnimplementedRpcPropertyServer()
}

// UnimplementedRpcPropertyServer must be embedded to have forward compatible implementations.
type UnimplementedRpcPropertyServer struct {
}

func (UnimplementedRpcPropertyServer) DeviceBatchReport(context.Context, *DeviceBatchReportRequest) (*common.CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceBatchReport not implemented")
}
func (UnimplementedRpcPropertyServer) mustEmbedUnimplementedRpcPropertyServer() {}

// UnsafeRpcPropertyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcPropertyServer will
// result in compilation errors.
type UnsafeRpcPropertyServer interface {
	mustEmbedUnimplementedRpcPropertyServer()
}

func RegisterRpcPropertyServer(s grpc.ServiceRegistrar, srv RpcPropertyServer) {
	s.RegisterService(&RpcProperty_ServiceDesc, srv)
}

func _RpcProperty_DeviceBatchReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceBatchReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcPropertyServer).DeviceBatchReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/batch.RpcProperty/DeviceBatchReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcPropertyServer).DeviceBatchReport(ctx, req.(*DeviceBatchReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcProperty_ServiceDesc is the grpc.ServiceDesc for RpcProperty service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcProperty_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "batch.RpcProperty",
	HandlerType: (*RpcPropertyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeviceBatchReport",
			Handler:    _RpcProperty_DeviceBatchReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "batch/batch.proto",
}
