// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.14.0
// source: platform/message.proto

package platform

import (
	context "context"
	common "github.com/winc-link/iot-cloud-proto/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RpcIotPlatformMessageClient is the client API for RpcIotPlatformMessage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcIotPlatformMessageClient interface {
	// 云平台给网关发送消息入口
	IotPlatformMessage(ctx context.Context, in *PlatformMessageRequest, opts ...grpc.CallOption) (*common.CommonResponse, error)
}

type rpcIotPlatformMessageClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcIotPlatformMessageClient(cc grpc.ClientConnInterface) RpcIotPlatformMessageClient {
	return &rpcIotPlatformMessageClient{cc}
}

func (c *rpcIotPlatformMessageClient) IotPlatformMessage(ctx context.Context, in *PlatformMessageRequest, opts ...grpc.CallOption) (*common.CommonResponse, error) {
	out := new(common.CommonResponse)
	err := c.cc.Invoke(ctx, "/platform.RpcIotPlatformMessage/IotPlatformMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcIotPlatformMessageServer is the server API for RpcIotPlatformMessage service.
// All implementations must embed UnimplementedRpcIotPlatformMessageServer
// for forward compatibility
type RpcIotPlatformMessageServer interface {
	// 云平台给网关发送消息入口
	IotPlatformMessage(context.Context, *PlatformMessageRequest) (*common.CommonResponse, error)
	mustEmbedUnimplementedRpcIotPlatformMessageServer()
}

// UnimplementedRpcIotPlatformMessageServer must be embedded to have forward compatible implementations.
type UnimplementedRpcIotPlatformMessageServer struct {
}

func (UnimplementedRpcIotPlatformMessageServer) IotPlatformMessage(context.Context, *PlatformMessageRequest) (*common.CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IotPlatformMessage not implemented")
}
func (UnimplementedRpcIotPlatformMessageServer) mustEmbedUnimplementedRpcIotPlatformMessageServer() {}

// UnsafeRpcIotPlatformMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcIotPlatformMessageServer will
// result in compilation errors.
type UnsafeRpcIotPlatformMessageServer interface {
	mustEmbedUnimplementedRpcIotPlatformMessageServer()
}

func RegisterRpcIotPlatformMessageServer(s grpc.ServiceRegistrar, srv RpcIotPlatformMessageServer) {
	s.RegisterService(&RpcIotPlatformMessage_ServiceDesc, srv)
}

func _RpcIotPlatformMessage_IotPlatformMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcIotPlatformMessageServer).IotPlatformMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/platform.RpcIotPlatformMessage/IotPlatformMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcIotPlatformMessageServer).IotPlatformMessage(ctx, req.(*PlatformMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcIotPlatformMessage_ServiceDesc is the grpc.ServiceDesc for RpcIotPlatformMessage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcIotPlatformMessage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform.RpcIotPlatformMessage",
	HandlerType: (*RpcIotPlatformMessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IotPlatformMessage",
			Handler:    _RpcIotPlatformMessage_IotPlatformMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform/message.proto",
}
