// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: platform/message.proto

package platform

import (
	common "github.com/winc-link/iot-cloud-proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_Custom      MessageType = 0 //自定义类型
	MessageType_PropertySet MessageType = 1 //属性设置
	MessageType_Command     MessageType = 2 //命令下发
	MessageType_Message     MessageType = 3 //消息下发
	MessageType_PropertyGet MessageType = 4 //属性查询
	MessageType_Event       MessageType = 5 //事件下发
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "Custom",
		1: "PropertySet",
		2: "Command",
		3: "Message",
		4: "PropertyGet",
		5: "Event",
	}
	MessageType_value = map[string]int32{
		"Custom":      0,
		"PropertySet": 1,
		"Command":     2,
		"Message":     3,
		"PropertyGet": 4,
		"Event":       5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_platform_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_platform_message_proto_rawDescGZIP(), []int{0}
}

type PlatformMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType MessageType                         `protobuf:"varint,1,opt,name=messageType,proto3,enum=platform.MessageType" json:"messageType,omitempty"`
	DeviceId    string                              `protobuf:"bytes,2,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	MessageInfo *PlatformMessageRequest_MessageInfo `protobuf:"bytes,3,opt,name=messageInfo,proto3" json:"messageInfo,omitempty"`
}

func (x *PlatformMessageRequest) Reset() {
	*x = PlatformMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatformMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformMessageRequest) ProtoMessage() {}

func (x *PlatformMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformMessageRequest.ProtoReflect.Descriptor instead.
func (*PlatformMessageRequest) Descriptor() ([]byte, []int) {
	return file_platform_message_proto_rawDescGZIP(), []int{0}
}

func (x *PlatformMessageRequest) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_Custom
}

func (x *PlatformMessageRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PlatformMessageRequest) GetMessageInfo() *PlatformMessageRequest_MessageInfo {
	if x != nil {
		return x.MessageInfo
	}
	return nil
}

type PlatformMessageRequest_MessageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic   string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *PlatformMessageRequest_MessageInfo) Reset() {
	*x = PlatformMessageRequest_MessageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatformMessageRequest_MessageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformMessageRequest_MessageInfo) ProtoMessage() {}

func (x *PlatformMessageRequest_MessageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_platform_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformMessageRequest_MessageInfo.ProtoReflect.Descriptor instead.
func (*PlatformMessageRequest_MessageInfo) Descriptor() ([]byte, []int) {
	return file_platform_message_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PlatformMessageRequest_MessageInfo) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PlatformMessageRequest_MessageInfo) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_platform_message_proto protoreflect.FileDescriptor

var file_platform_message_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfc, 0x01, 0x0a, 0x16, 0x50, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x37, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x4e, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x3d, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2a, 0x60, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x10,
	0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x53, 0x65, 0x74,
	0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x10, 0x02, 0x12,
	0x0b, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b,
	0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x47, 0x65, 0x74, 0x10, 0x04, 0x12, 0x09, 0x0a,
	0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x10, 0x05, 0x32, 0x69, 0x0a, 0x15, 0x52, 0x70, 0x63, 0x49,
	0x6f, 0x74, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x50, 0x0a, 0x12, 0x49, 0x6f, 0x74, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x77, 0x69, 0x6e, 0x63, 0x2d, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x69, 0x6f, 0x74, 0x2d,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_platform_message_proto_rawDescOnce sync.Once
	file_platform_message_proto_rawDescData = file_platform_message_proto_rawDesc
)

func file_platform_message_proto_rawDescGZIP() []byte {
	file_platform_message_proto_rawDescOnce.Do(func() {
		file_platform_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_platform_message_proto_rawDescData)
	})
	return file_platform_message_proto_rawDescData
}

var file_platform_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_platform_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_platform_message_proto_goTypes = []interface{}{
	(MessageType)(0),                           // 0: platform.messageType
	(*PlatformMessageRequest)(nil),             // 1: platform.PlatformMessageRequest
	(*PlatformMessageRequest_MessageInfo)(nil), // 2: platform.PlatformMessageRequest.MessageInfo
	(*common.CommonResponse)(nil),              // 3: common.CommonResponse
}
var file_platform_message_proto_depIdxs = []int32{
	0, // 0: platform.PlatformMessageRequest.messageType:type_name -> platform.messageType
	2, // 1: platform.PlatformMessageRequest.messageInfo:type_name -> platform.PlatformMessageRequest.MessageInfo
	1, // 2: platform.RpcIotPlatformMessage.IotPlatformMessage:input_type -> platform.PlatformMessageRequest
	3, // 3: platform.RpcIotPlatformMessage.IotPlatformMessage:output_type -> common.CommonResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_platform_message_proto_init() }
func file_platform_message_proto_init() {
	if File_platform_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_platform_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatformMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatformMessageRequest_MessageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_platform_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_platform_message_proto_goTypes,
		DependencyIndexes: file_platform_message_proto_depIdxs,
		EnumInfos:         file_platform_message_proto_enumTypes,
		MessageInfos:      file_platform_message_proto_msgTypes,
	}.Build()
	File_platform_message_proto = out.File
	file_platform_message_proto_rawDesc = nil
	file_platform_message_proto_goTypes = nil
	file_platform_message_proto_depIdxs = nil
}
