// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: property/property.proto

package property

import (
	common "github.com/winc-link/iot-cloud-proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DevicePropertyReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseMessage *DevicePropertyReportRequest_BaseMessage `protobuf:"bytes,1,opt,name=baseMessage,proto3" json:"baseMessage,omitempty"`
	Data        string                                   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	DeviceId    string                                   `protobuf:"bytes,3,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	ProductId   string                                   `protobuf:"bytes,4,opt,name=productId,proto3" json:"productId,omitempty"`
}

func (x *DevicePropertyReportRequest) Reset() {
	*x = DevicePropertyReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_property_property_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DevicePropertyReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevicePropertyReportRequest) ProtoMessage() {}

func (x *DevicePropertyReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_property_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevicePropertyReportRequest.ProtoReflect.Descriptor instead.
func (*DevicePropertyReportRequest) Descriptor() ([]byte, []int) {
	return file_property_property_proto_rawDescGZIP(), []int{0}
}

func (x *DevicePropertyReportRequest) GetBaseMessage() *DevicePropertyReportRequest_BaseMessage {
	if x != nil {
		return x.BaseMessage
	}
	return nil
}

func (x *DevicePropertyReportRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *DevicePropertyReportRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DevicePropertyReportRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type DevicePropertyReportRequest_BaseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version   string                                       `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
	MessageId string                                       `protobuf:"bytes,2,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	Sys       *DevicePropertyReportRequest_BaseMessage_Sys `protobuf:"bytes,3,opt,name=sys,proto3" json:"sys,omitempty"`
}

func (x *DevicePropertyReportRequest_BaseMessage) Reset() {
	*x = DevicePropertyReportRequest_BaseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_property_property_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DevicePropertyReportRequest_BaseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevicePropertyReportRequest_BaseMessage) ProtoMessage() {}

func (x *DevicePropertyReportRequest_BaseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_property_property_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevicePropertyReportRequest_BaseMessage.ProtoReflect.Descriptor instead.
func (*DevicePropertyReportRequest_BaseMessage) Descriptor() ([]byte, []int) {
	return file_property_property_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DevicePropertyReportRequest_BaseMessage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DevicePropertyReportRequest_BaseMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DevicePropertyReportRequest_BaseMessage) GetSys() *DevicePropertyReportRequest_BaseMessage_Sys {
	if x != nil {
		return x.Sys
	}
	return nil
}

type DevicePropertyReportRequest_BaseMessage_Sys struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack uint32 `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (x *DevicePropertyReportRequest_BaseMessage_Sys) Reset() {
	*x = DevicePropertyReportRequest_BaseMessage_Sys{}
	if protoimpl.UnsafeEnabled {
		mi := &file_property_property_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DevicePropertyReportRequest_BaseMessage_Sys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevicePropertyReportRequest_BaseMessage_Sys) ProtoMessage() {}

func (x *DevicePropertyReportRequest_BaseMessage_Sys) ProtoReflect() protoreflect.Message {
	mi := &file_property_property_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevicePropertyReportRequest_BaseMessage_Sys.ProtoReflect.Descriptor instead.
func (*DevicePropertyReportRequest_BaseMessage_Sys) Descriptor() ([]byte, []int) {
	return file_property_property_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *DevicePropertyReportRequest_BaseMessage_Sys) GetAck() uint32 {
	if x != nil {
		return x.Ack
	}
	return 0
}

var File_property_property_proto protoreflect.FileDescriptor

var file_property_property_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x79, 0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xea, 0x02, 0x0a, 0x1b, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x53, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e,
	0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x1a, 0xa7, 0x01, 0x0a, 0x0b,
	0x42, 0x61, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x64, 0x12, 0x47, 0x0a, 0x03, 0x73, 0x79, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x35, 0x2e, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x2e, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x53, 0x79, 0x73, 0x52, 0x03, 0x73, 0x79, 0x73, 0x1a, 0x17, 0x0a, 0x03,
	0x53, 0x79, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x61, 0x63, 0x6b, 0x32, 0x66, 0x0a, 0x0b, 0x52, 0x70, 0x63, 0x50, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x79, 0x12, 0x57, 0x0a, 0x14, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x25, 0x2e, 0x70,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2f, 0x5a,
	0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x69, 0x6e, 0x63,
	0x2d, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x69, 0x6f, 0x74, 0x2d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_property_property_proto_rawDescOnce sync.Once
	file_property_property_proto_rawDescData = file_property_property_proto_rawDesc
)

func file_property_property_proto_rawDescGZIP() []byte {
	file_property_property_proto_rawDescOnce.Do(func() {
		file_property_property_proto_rawDescData = protoimpl.X.CompressGZIP(file_property_property_proto_rawDescData)
	})
	return file_property_property_proto_rawDescData
}

var file_property_property_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_property_property_proto_goTypes = []interface{}{
	(*DevicePropertyReportRequest)(nil),                 // 0: property.DevicePropertyReportRequest
	(*DevicePropertyReportRequest_BaseMessage)(nil),     // 1: property.DevicePropertyReportRequest.BaseMessage
	(*DevicePropertyReportRequest_BaseMessage_Sys)(nil), // 2: property.DevicePropertyReportRequest.BaseMessage.Sys
	(*common.CommonResponse)(nil),                       // 3: common.CommonResponse
}
var file_property_property_proto_depIdxs = []int32{
	1, // 0: property.DevicePropertyReportRequest.baseMessage:type_name -> property.DevicePropertyReportRequest.BaseMessage
	2, // 1: property.DevicePropertyReportRequest.BaseMessage.sys:type_name -> property.DevicePropertyReportRequest.BaseMessage.Sys
	0, // 2: property.RpcProperty.DevicePropertyReport:input_type -> property.DevicePropertyReportRequest
	3, // 3: property.RpcProperty.DevicePropertyReport:output_type -> common.CommonResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_property_property_proto_init() }
func file_property_property_proto_init() {
	if File_property_property_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_property_property_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DevicePropertyReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_property_property_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DevicePropertyReportRequest_BaseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_property_property_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DevicePropertyReportRequest_BaseMessage_Sys); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_property_property_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_property_property_proto_goTypes,
		DependencyIndexes: file_property_property_proto_depIdxs,
		MessageInfos:      file_property_property_proto_msgTypes,
	}.Build()
	File_property_property_proto = out.File
	file_property_property_proto_rawDesc = nil
	file_property_property_proto_goTypes = nil
	file_property_property_proto_depIdxs = nil
}
